//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace c_project.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public task()
        {
            this.userdatas = new HashSet<userdata>();
        }
    
        public int t_id { get; set; }
        public int p_id { get; set; }
        public string t_name { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> date_time_created { get; set; }
        public Nullable<System.DateTime> date_time_finish { get; set; }
        public Nullable<int> t_status { get; set; }
    
        public virtual project project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userdata> userdatas { get; set; }
    }
}
